[phases.setup]
nixPkgs = ["python311", "postgresql"]

[phases.install]
cmds = [
  "python -m ensurepip",
  "python -m pip install --upgrade pip",
  "cd backend && python -m pip install -r requirements.txt"
]

[start]
cmd = "cd backend && gunicorn app:app --bind 0.0.0.0:$PORT"
